# Generated by Django 6.0.6 on 2026-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_cs', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('short_desc', models.CharField(max_length=300)),
                ('short_desc_cs', models.CharField(max_length=300, null=True)),
                ('short_desc_en', models.CharField(max_length=300, null=True)),
                ('short_desc_ru', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_cs', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('duration_min', models.PositiveIntegerField(default=60)),
                ('duration_max', models.PositiveIntegerField(default=90)),
                ('price_czk', models.PositiveIntegerField()),
                ('price_label', models.CharField(blank=True, help_text='e.g. od 500 Kč', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_title_cs', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_description_cs', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
