# Generated by Django 4.2.30 on 2026-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_eur',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_usd',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
