# Generated by Django 4.2.30 on 2026-06-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_cloudinaryimage_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('privacy', 'Privacy Policy'), ('first_visit', 'First Visit'), ('prices', 'Price list'), ('jobs', 'Jobs')], max_length=32, unique=True, verbose_name='Page')),
                ('body_cs', models.TextField(blank=True, verbose_name='Body (Czech, HTML)')),
                ('body_en', models.TextField(blank=True, verbose_name='Body (English, HTML)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Body (Russian, HTML)')),
                ('hero_sub_cs', models.CharField(blank=True, help_text='Optional. Shown under the page title when filled.', max_length=300, verbose_name='Hero subtitle (Czech)')),
                ('hero_sub_en', models.CharField(blank=True, max_length=300, verbose_name='Hero subtitle (English)')),
                ('hero_sub_ru', models.CharField(blank=True, max_length=300, verbose_name='Hero subtitle (Russian)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Content',
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('behavior', 'Behavior'), ('hygiene', 'Hygiene'), ('privacy', 'Privacy'), ('booking', 'Booking & Cancellation')], max_length=20, verbose_name='Category')),
                ('rule_cs', models.TextField(verbose_name='Rule (Czech)')),
                ('rule_en', models.TextField(blank=True, verbose_name='Rule (English)')),
                ('rule_ru', models.TextField(blank=True, verbose_name='Rule (Russian)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Etiquette rule',
                'verbose_name_plural': 'Etiquette rules',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GuestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_cs', models.TextField(verbose_name='Review (Czech)')),
                ('text_en', models.TextField(blank=True, verbose_name='Review (English)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Review (Russian)')),
                ('author_label', models.CharField(help_text='e.g. M. K.', max_length=40, verbose_name='Author')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='City')),
                ('google_review_id', models.CharField(blank=True, db_index=True, help_text='Stable ID from Google Places API (for sync).', max_length=120, null=True, unique=True, verbose_name='Google review ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Star rating (1–5) from Google.', null=True, verbose_name='Rating')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest review',
                'verbose_name_plural': 'Guest reviews',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LegacyRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, help_text='e.g. /cs/nuru-masaz/ or /klasicka-eroticka-masaz/', max_length=500, unique=True, verbose_name='Old path')),
                ('new_path', models.CharField(blank=True, help_text='Leave blank to redirect to /. Use full path e.g. /cs/services/nuru/', max_length=500, verbose_name='New path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legacy Redirect',
                'verbose_name_plural': 'Legacy Redirects',
                'ordering': ['old_path'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування сайту', 'verbose_name_plural': 'Налаштування сайту'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Lužická 1416/29, Vinohrady, 120 00 Praha 2', max_length=200, verbose_name='Адреса (студія 1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адреса (студія 2)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description за замовчуванням'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title за замовчуванням'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@black-velvet.cz', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(default='Po–Pá 10:00–21:00, So–Ne 10:00–19:00', max_length=100, verbose_name='Години роботи (CS)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Години роботи (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Години роботи (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_phone_1',
            field=models.CharField(default='+420 778 622 334', max_length=30, verbose_name='Телефон (студія 1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_phone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон (студія 2)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Посилання на карту (студія 1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url_2',
            field=models.URLField(blank=True, max_length=500, verbose_name='Посилання на карту (студія 2)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maps_embed_url',
            field=models.TextField(blank=True, verbose_name='Google Maps embed URL (студія 1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maps_embed_url_2',
            field=models.TextField(blank=True, verbose_name='Google Maps embed URL (студія 2)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image_url',
            field=models.URLField(blank=True, verbose_name='OG image URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='+420 778 622 334', max_length=30, verbose_name='Основний телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_rotation_hours',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Інтервал ротації (год)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Додатковий телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_age_confirmation',
            field=models.BooleanField(default=True, verbose_name='Підтвердження 18+'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rotation_phone_1',
            field=models.CharField(default='+420 778 622 334', max_length=30, verbose_name='Ротаційний телефон 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rotation_phone_2',
            field=models.CharField(default='+420 778 622 334', max_length=30, verbose_name='Ротаційний телефон 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rotation_phone_3',
            field=models.CharField(default='+420 778 622 334', max_length=30, verbose_name='Ротаційний телефон 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='420778622334', help_text='Напр. 420778622334 — для wa.me/', max_length=20, verbose_name='WhatsApp (без + і пробілів)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp URL'),
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='interior/', verbose_name='Uploaded image')),
                ('static_path', models.CharField(blank=True, help_text='Relative to static/, e.g. src/img/interior/photo.jpg', max_length=255, verbose_name='Static file path')),
                ('alt_cs', models.CharField(blank=True, max_length=300, verbose_name='Alt text (Czech)')),
                ('alt_en', models.CharField(blank=True, max_length=300, verbose_name='Alt text (English)')),
                ('alt_ru', models.CharField(blank=True, max_length=300, verbose_name='Alt text (Russian)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloudinary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_usages', to='media_library.cloudinaryimage', verbose_name='Cloudinary image')),
            ],
            options={
                'verbose_name': 'Interior photo',
                'verbose_name_plural': 'Interior photos',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
