# Generated by Django 6.0.6 on 2026-06-12 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_cs', models.CharField(max_length=80, null=True)),
                ('name_en', models.CharField(max_length=80, null=True)),
                ('name_ru', models.CharField(max_length=80, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_cs', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('excerpt_cs', models.TextField(max_length=300, null=True)),
                ('excerpt_en', models.TextField(max_length=300, null=True)),
                ('excerpt_ru', models.TextField(max_length=300, null=True)),
                ('content', models.TextField()),
                ('content_cs', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('author_name', models.CharField(default='Black Velvet', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_title_cs', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_description_cs', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
