# Generated by Django 6.0.6 on 2026-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masseuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('bio', models.TextField()),
                ('bio_cs', models.TextField(null=True)),
                ('bio_en', models.TextField(null=True)),
                ('bio_ru', models.TextField(null=True)),
                ('specializations', models.CharField(max_length=200)),
                ('specializations_cs', models.CharField(max_length=200, null=True)),
                ('specializations_en', models.CharField(max_length=200, null=True)),
                ('specializations_ru', models.CharField(max_length=200, null=True)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_title_cs', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_description_cs', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('services', models.ManyToManyField(blank=True, related_name='masseuses', to='services.service')),
            ],
            options={
                'verbose_name': 'Masseuse',
                'verbose_name_plural': 'Masseuses',
                'ordering': ['order', 'name'],
            },
        ),
    ]
