# Generated by Django 4.2.30 on 2026-06-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_cloudinaryimage_options'),
        ('team', '0003_migrate_masseuse_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masseuse',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Масажистка', 'verbose_name_plural': 'Масажистки'},
        ),
        migrations.AddField(
            model_name='masseuse',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='bust',
            field=models.CharField(blank=True, max_length=10, verbose_name='Груди'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='gallery_cloudinary',
            field=models.ManyToManyField(blank=True, related_name='masseuse_gallery', to='media_library.cloudinaryimage', verbose_name='Галерея (Cloudinary)'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='has_location',
            field=models.BooleanField(default=True, verbose_name='Є локація'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='has_schedule',
            field=models.BooleanField(default=True, verbose_name='Є розклад'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Зріст (см)'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='Зайнята'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Нова'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='main_cloudinary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masseuse_main', to='media_library.cloudinaryimage', verbose_name='Головне фото (Cloudinary)'),
        ),
        migrations.AddField(
            model_name='masseuse',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вага (кг)'),
        ),
    ]
