# Generated by Django 6.0.4 on 2026-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(choices=[('general', 'General / No service'), ('nuru', 'Nuru'), ('lingam', 'Lingam'), ('body', 'Body-to-Body'), ('bdsm', 'BDSM'), ('vip', 'VIP'), ('couple', 'Couples'), ('classic', 'Classic Erotic'), ('pussycat', 'Pussycat'), ('prostate', 'Prostate')], default='general', max_length=30, unique=True, verbose_name='Service key')),
                ('template_cs', models.TextField(help_text='Use {masseuse} and {duration} placeholders.', verbose_name='Message template (CS)')),
                ('template_en', models.TextField(blank=True, verbose_name='Message template (EN)')),
                ('template_ru', models.TextField(blank=True, verbose_name='Message template (RU)')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
    ]
