# Generated by Django 4.2.30 on 2026-06-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingclick_ip_only_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingclick',
            new_name='booking_boo_clicked_ea19a3_idx',
            old_name='booking_cl_clicked_7a8b2d_idx',
        ),
    ]
