# Generated by Django 6.0.6 on 2026-06-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('question_cs', models.CharField(max_length=300, null=True)),
                ('question_en', models.CharField(max_length=300, null=True)),
                ('question_ru', models.CharField(max_length=300, null=True)),
                ('answer', models.TextField()),
                ('answer_cs', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('page', models.CharField(choices=[('home', 'Home'), ('service', 'Service'), ('general', 'General')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_cs', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Price categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('role_cs', models.CharField(blank=True, max_length=100, null=True)),
                ('role_en', models.CharField(blank=True, max_length=100, null=True)),
                ('role_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('text_cs', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_name_cs', models.CharField(max_length=150, null=True)),
                ('service_name_en', models.CharField(max_length=150, null=True)),
                ('service_name_ru', models.CharField(max_length=150, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('note_cs', models.CharField(blank=True, max_length=200, null=True)),
                ('note_en', models.CharField(blank=True, max_length=200, null=True)),
                ('note_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pricecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
