# Generated by Django 4.2.30 on 2026-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='include_in_schema',
            field=models.BooleanField(default=True, verbose_name='У schema.org'),
        ),
    ]
