# Generated by Django 4.2.30 on 2026-06-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_masseuse_options_masseuse_age_masseuse_bust_and_more'),
        ('pages', '0002_faq_include_in_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Work location',
                'verbose_name_plural': 'Work locations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='priceitem',
            name='price_czk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='price_eur',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='price_usd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MasseuseShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = Monday … 6 = Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='pages.worklocation')),
                ('masseuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='team.masseuse')),
            ],
            options={
                'verbose_name': 'Masseuse shift',
                'verbose_name_plural': 'Masseuse shifts',
                'ordering': ['weekday', 'order', 'start_time'],
            },
        ),
    ]
