# Generated by Django 4.2.30 on 2026-06-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudinaryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
